name: Package

on: [push]

jobs:
  test:    
    runs-on: self-hosted
    name: Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          TAG=hw-description-$(uuidgen) # Add a GUID to prevent clashes
          docker build .devcontainer --tag $TAG
          docker run --rm \
            -v `pwd`:/workspace \
            -w /workspace \
            $TAG \
            ./test.sh

  package_job:

    # Only run if the tests pass
    needs: test

    runs-on: [self-hosted, conda-feed]
    name: Conda Packaging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish
        run: |
          ${{ secrets.CONDA_SCRIPTS_DIR }}/publish.sh \
            ${{ secrets.STORAGE_ACCOUNT_KEY }} \
            `pwd` \
            ndscan
